### ISSUE TITLE
lenient ewts search?

### ISSUE THREAD

**Issue by eroux** [buda-base/lucene-bo#26]
We already are quite lenient in the ewts search... but it seems we're not lenient enough, as for instance *Dgongs pa rab gsal* doesn't return any result on BUDA, while it does on tbrc.org... @xristy do you know what leads tbrc.org to return results here? is the analyzer lowercasing the ewts?

**Comment by eroux** [comment]
For lower case search there are a few "lenient" ewts things to implement:
- lower casing letters other than GKCBL which are currently lower cased: HENJP
- having a lenient Sanskrit mode that lower cases everything?

**Comment by xristy** [comment]
the [lucene analyzer code for tbrc.org](https://github.com/tibetan-nlp/lucene-analyzers/tree/master/src/org/tbrc/lucene/analysis) may help. I'll continue to look further.

**Comment by eroux** [comment]
thanks! I looked at that this morning but there doesn't seem to be anything related in there... nor in https://github.com/tibetan-nlp/sorting-and-conversion/ although I was sort of hoping to find something... maybe somewhere in the gwt code there's a tolower on the searched string before it's passed to the server?

**Comment by xristy** [comment]
In particular eXist-db is configured to use `org.tbrc.lucene.analysis.WylieAnalyzer` for titles, notes, descriptions, log entries and so on.

**Comment by eroux** [comment]
thanks! I'm wondering: perhaps it's the xquery that lower cases the search string?

**Comment by xristy** [comment]
Here's the flow from the user input to Lucene, via `ft:query`.  I don't see anything lower-casing or what not but there must be something somewhere in the following and the `org.tbrc.lucene.analysis.WylieAnalyzer` that accounts for the tbrc.org search behavior.

The query string entered by the user is processed in the client:
```
    String pattern = Utils.query2luceneIndium(toWylie(query));
    String uniPattern = Utils.query2luceneIndium(converter.toUnicode(query));
    . . .
    String[] types = new String[] { "outlines", "works", "pages" };
    . . .
    fvsa.queryWithTaxonomyTree("global-search", "main", locale, new String[] { pattern, uniPattern, limit }, types, searchCallback);
```

The `pattern` is the query entered by the user rewritten in Lucene query syntax:
```
	public static String query2luceneIndium(String query) {
		if (query == null || query.isEmpty()) {
			return "";
		}
		
		// get rid of leading and trailing ' ' and repeated ' '
		query = squeeze(query);
		
		StringBuilder lucene = new StringBuilder();

		char[] chars = query.toCharArray();
		boolean inQ = false;
		
		for (char c : chars) {
			if (c == '"') {
				inQ = ! inQ;
				lucene.append("&quot;");
			} else if (! inQ && c == ' ') {
				lucene.append(" AND ");
			} else {
				lucene.append(c);
			}
		}

		GWT.log("Utils.query2lucene: " + query + " >>> " + lucene.toString());
		return lucene.toString();
	}
```

The `fvsa.queryWithTaxonomyTree` sends the `pattern` to eXist-db (now called `$qryString`) which is processed like:
```
    let $termStr := replace($qryString, '"', '')
    let $terms := tokenize($termStr, " ")
    let $query := q:query($terms)
    let $titles0 := collection('/db/tbrc/tbrc-works/')//w:title[ft:query(., $query)]

declare function q:query($terms as xs:string*)
as element()?
{
    let $n := count($terms)
    let $m := $n idiv 2
    let $j := ($n + 3) idiv 2
    let $nears :=
        if ($n le 2) then
            <near order="yes" slop="0">{ $terms }</near>
        else if ($n le 4) then
            <near order="yes" slop="1">{ $terms }</near>
        else if ($n le 20) then
            for $s in 1 to $m
            let $ts := 
                for $t in subsequence($terms, $s, $j)
                return
                    <term>{ $t }</term>
            return
                <near order="yes" slop="1">{ $ts }</near>
        else
            <near order="yes" slop="1">{ $terms }</near>
    return
       <query>{ $nears }</query>
};
```

The `$titles` and similar are returned to the client app as the search results.

**Comment by xristy** [comment]
It is worth noting that [WylieTokenizer.normalize](https://github.com/tibetan-nlp/lucene-analyzers/blob/20e4b67fc9d920fdb2a91bf60d9a381e0370feb0/src/org/tbrc/lucene/analysis/WylieTokenizer.java#L105) does `Character.toLowerCase(c)`.

**Comment by eroux** [comment]
aaaaah right, thanks a lot! Sorry for not spotting that... I think I stupidly searched (on github) on "tolower" instead of "tolowercase"... well... now at least I undestand what's going on... I'm not entirely sure what's best but I'll handle it!

**Comment by eroux** [comment]
moved to https://github.com/buda-base/public-digital-library/issues/215
