### ISSUE TITLE
Request for new normalization rule for the verb འབྱོན་ to account for over-corrections in our catalog

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/lucene-bo#39]
Please allow for བྱོན་ to be read as འབྱོན་ and vice versa 

I just saw a reference to a text title written as sku skye myur 'byon gyi de nyid gsal byed and it caught my attention so I looked it up on BUDA. Zero results were returned and I was surprised. Then I tried it with a different verb stem of འབྱོན་ (i.e., བྱོན་) and found the text I wanted; we have 4 versions of it. And to complicate matters even more, the spelling of the title in the text itself has འབྱོན་ but BDRC's catalog records corrected it to བྱོན་ and didn't note both spellings so users are at a disadvantage.

**Comment by karmagongde** [comment]
Hi @eroux where do I see the outline number of the works on the BUDA? To correct these, I have to check out the outline number of the individual Work number. 
On tbrc.org, all the outline numbers can find on the URL of a particular work number.

**Comment by karmagongde** [comment]
Hi @JannTibetan Corrected the typo on the outline node title "sku skye myur 'byon gyi de nyid gsal byed".

**Comment by JannTibetan** [comment]
> Thanks Jann! I'm going to update the text index quite soon so if you think if other normalizations don't hesitate (it's quite rare that we update it, ir's a big operation)

OK I'll try to think of some other normalizations that wee might have missed before.

**Comment by JannTibetan** [comment]
> Hi @JannTibetan Corrected the typo on the outline node title "sku skye myur 'byon gyi de nyid gsal byed".

Thanks @karmagongde!

**Comment by eroux** [comment]
Hi @karmagongde thanks for the change! The tbrc.org outline node IDs are not currently displayed on BUDA, I'll make them accessible to admin users

**Comment by eroux** [comment]
fixed (not deployed yet)
