### ISSUE TITLE
Normalization of Mongolian names and terms

### ISSUE THREAD

**Issue by JannTibetan** [buda-base/lucene-bo#41]
I just did a search on [mer gin mkhan po](https://library.bdrc.io/search?q=%22mer%20gin%20mkhan%20po%22~1&lg=bo-x-ewts&t=Instance&f=asset,inc,tmp:possibleAccess&f=asset,inc,tmp:catalogOnly) and found that mer gin appears in various ways in our sources and therefore in our metadata. 
The search engine already does a good job being lenient about the second syllable of the string "mer gin mkhan po." In the search results we find:
mer gin
mer gan
mer gen
mer rgan
mer khan
mer mkhan

**Comment by eroux** [comment]
well... it's sort of unattended! What happens is that the search engine ignores the particle `གིན`, so it that case it only search on `mer`, which probably returns the relevant results but could very well return other non-relevant ones. Very interesting use case though, thanks!

**Comment by JannTibetan** [comment]
Does that mean that a search on mer rgan won't return the same diversity of results?

**Comment by eroux** [comment]
indeed, because the search engine won't ignore `rgan`

**Comment by JannTibetan** [comment]
If some Mongolianists are able to provide a substantial list of variant spellings of important Mongolian words, how long would it take to add those normalizations to our search? It's not urgent because in our communications about the NLM collection we can advise people to search on variants as our metadata reflects the spelling in the texts as-is, without changes.

**Comment by eroux** [comment]
integrating a list of normalization like this in the search engine is not too difficult, if I get a simple csv file with two columns it can get integrated in the code in a few minutes. OTOH, deploying a new version of the search engine requires an awful lot of work because everything needs to be re-indexed, including the etexts. So probably a day or two, including some manual work

**Comment by eroux** [comment]
(note that the normalization of the phonetics of non-Tibetan languages in Tibetan is a pretty big issue that I don't think we can solve soon. This is very prominent for Sanskrit for instance, there's probably a good impact to have there, but I can't really think of a plan to get us there, there's just too much to normalize...)

**Comment by JannTibetan** [comment]
Understood and thanks for explaining. I don't want to disrupt our other work for this as Mongolianists who work on Tibetan texts should already be very familiar with all the variant spellings for Khan and so on.

**Comment by eroux** [comment]
implement this in the current state will be too disruptive, let's do it later maybe
